// ADMIN ADD PRODUCT

export const ADMIN_ADD_PRODUCT_REQUEST = "ADMIN_ADD_PRODUCT_REQUEST";
export const ADMIN_ADD_PRODUCT_SUCESS = "ADMIN_ADD_PRODUCT_SUCESS";
export const ADMIN_ADD_PRODUCT_FAIL = "ADMIN_ADD_PRODUCT_FAIL";


// GET PRODUCT

export const ADMIN_GET_PRODUCT_REQUEST = "ADMIN_GET_PRODUCT_REQUEST";
export const ADMIN_GET_PRODUCT_SUCESS = "ADMIN_GET_PRODUCT_SUCESS";
export const ADMIN_GET_PRODUCT_FAIL = "ADMIN_GET_PRODUCT_FAIL";

// DELETE PRODUCT

export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCESS = "ADMIN_DELETE_PRODUCT_SUCESS";
export const ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL";

// UPDATE PRODUCT

export const ADMIN_ADD_UPDATE_REQUEST = "ADMIN_ADD_UPDATE_REQUEST";
export const ADMIN_ADD_UPDATE_SUCESS = "ADMIN_ADD_UPDATE_SUCESS";
export const ADMIN_ADD_UPDATE_FAIL = "ADMIN_ADD_UPDATE_FAIL";

